### ISSUE TITLE
Deleting Product Type not possible when referenced elsewhere

### ISSUE THREAD

**Issue by leonstiegler** [taranis-ai/taranis-ai#297]
As described in the title it is not possible to delete a product type if it is referenced elsewhere.

There is no indication of the problem when deleteting (see screenshot):
![image](https://github.com/user-attachments/assets/e42331f7-c3f2-41fb-80de-2acd7f95c0ee)

Only when looking at the logs you can see the issue:
```
database-1   | 2024-07-31 12:55:38.431 UTC [1122236] ERROR:  update or delete on table "report_item_type" violates foreign key constraint "product_type_report_type_report_item_type_id_fkey" on table "product_type_report_type"
database-1   | 2024-07-31 12:55:38.431 UTC [1122236] DETAIL:  Key (id)=(5) is still referenced from table "product_type_report_type".
database-1   | 2024-07-31 12:55:38.431 UTC [1122236] STATEMENT:  DELETE FROM report_item_type WHERE report_item_type.id = 5
core-1       | [Core] [ERROR] - Exception on /api/config/product-types/11 [DELETE]
core-1       | Traceback (most recent call last):
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
core-1       |     self.dialect.do_execute(
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
core-1       |     cursor.execute(statement, parameters)
core-1       | psycopg2.errors.ForeignKeyViolation: update or delete on table "report_item_type" violates foreign key constraint "product_type_report_type_report_item_type_id_fkey" on table "product_type_report_type"
core-1       | DETAIL:  Key (id)=(5) is still referenced from table "product_type_report_type".
core-1       |
core-1       |
core-1       | The above exception was the direct cause of the following exception:
core-1       |
core-1       | Traceback (most recent call last):
core-1       |   File "/app/.venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
core-1       |     response = self.full_dispatch_request()
core-1       |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
core-1       |   File "/app/.venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
core-1       |     rv = self.handle_user_exception(e)
core-1       |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
core-1       |   File "/app/.venv/lib/python3.12/site-packages/flask_cors/extension.py", line 178, in wrapped_function
core-1       |     return cors_after_request(app.make_response(f(*args, **kwargs)))
core-1       |                                                 ^^^^^^^^^^^^^^^^^^
core-1       |   File "/app/.venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
core-1       |     rv = self.dispatch_request()
core-1       |          ^^^^^^^^^^^^^^^^^^^^^^^
core-1       |   File "/app/.venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
core-1       |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
core-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
core-1       |   File "/app/.venv/lib/python3.12/site-packages/flask/views.py", line 110, in view
core-1       |     return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
core-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
core-1       |   File "/app/.venv/lib/python3.12/site-packages/flask/views.py", line 191, in dispatch_request
core-1       |     return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
core-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
core-1       |   File "/app/core/managers/auth_manager.py", line 97, in wrapper
core-1       |     return fn(*args, **kwargs)
core-1       |            ^^^^^^^^^^^^^^^^^^^
core-1       |   File "/app/core/api/config.py", line 159, in delete
core-1       |     return product_type.ProductType.delete(type_id)
core-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
core-1       |   File "/app/core/model/base_model.py", line 57, in delete
core-1       |     db.session.commit()
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
core-1       |     return self._proxied.commit()
core-1       |            ^^^^^^^^^^^^^^^^^^^^^^
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2017, in commit
core-1       |     trans.commit(_to_root=True)
core-1       |   File "<string>", line 2, in commit
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
core-1       |     ret_value = fn(self, *arg, **kw)
core-1       |                 ^^^^^^^^^^^^^^^^^^^^
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1302, in commit
core-1       |     self._prepare_impl()
core-1       |   File "<string>", line 2, in _prepare_impl
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
core-1       |     ret_value = fn(self, *arg, **kw)
core-1       |                 ^^^^^^^^^^^^^^^^^^^^
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1277, in _prepare_impl
core-1       |     self.session.flush()
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4341, in flush
core-1       |     self._flush(objects)
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4476, in _flush
core-1       |     with util.safe_reraise():
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
core-1       |     raise exc_value.with_traceback(exc_tb)
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4437, in _flush
core-1       |     flush_context.execute()
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
core-1       |     rec.execute(self)
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 679, in execute
core-1       |     util.preloaded.orm_persistence.delete_obj(
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 193, in delete_obj
core-1       |     _emit_delete_statements(
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 1465, in _emit_delete_statements
core-1       |     c = connection.execute(
core-1       |         ^^^^^^^^^^^^^^^^^^^
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
core-1       |     return meth(
core-1       |            ^^^^^
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
core-1       |     return connection._execute_clauseelement(
core-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
core-1       |     ret = self._execute_context(
core-1       |           ^^^^^^^^^^^^^^^^^^^^^^
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
core-1       |     return self._exec_single_context(
core-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
core-1       |     self._handle_dbapi_exception(
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2353, in _handle_dbapi_exception
core-1       |     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
core-1       |     self.dialect.do_execute(
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
core-1       |     cursor.execute(statement, parameters)
core-1       | sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) update or delete on table "report_item_type" violates foreign key constraint "product_type_report_type_report_item_type_id_fkey" on table "product_type_report_type"
core-1       | DETAIL:  Key (id)=(5) is still referenced from table "product_type_report_type".
core-1       |
core-1       | [SQL: DELETE FROM report_item_type WHERE report_item_type.id = %(id)s]
core-1       | [parameters: {'id': 5}]
core-1       | (Background on this error at: https://sqlalche.me/e/20/gkpj)
```

This behavior somewhat makes sense, there should be at least some kind of feedback though.
If a cascading delete is applicable/possible here should be discused.

**Comment by b3n4kh** [comment]
Fixed with: https://github.com/taranis-ai/taranis-ai/commit/268447504b39c0200f264d8b9cf06a97caf931a6

**Comment by leonstiegler** [comment]
As promised in the last telco I tried deleting the Product Types again (on 0.9.5 and on master from last week friday i think) and I still get the same 500 error message and the same exception in the log.

Also did something change in the DB in the lastest release? 
I just noticed our Reports and Products vanished with the update. Maybe there is a connection to the issue?
